### ISSUE TITLE
exer_5_0: Neue Biene wird erst beim zweiten Klick erzeugt

### ISSUE THREAD

**Issue by RedImp1470** [moritzgiuliani/mkb_eia2#1]
Falls du noch nicht selbst auf die Lösung gekommen bist:

In canvasObject.ts in der Funktion "addElement" fügst du den Arrays _xPos und _yPos neue Werte an der _n ten Stelle hinzu.
Das führt beim ersten Klick dazu, dass im Array _xPos für Index 11 der neue Wert eingetragen wird. Da das Array vor dem Einfügen aber nur Indizes von 0-9 (!) enthält kann in script.ts, Funktion animate() nicht der Wert für Index 10 (hier "xBee[10]") verwendet werden, was dir dann für xBee[10] NaN ausgibt. --> die Biene wird nicht gezeichnet.

Das Problem lasst sich also mit einer kleinen Änderung in canvasObject.ts in der Funktion "addElement" lösen, schau dir das Array _xPos oder _yPos am Besten mal im Debugger an.... :-) 

PS: Die Verwendung von Math.max() ist dort nicht nötig.

**Comment by moritzgiuliani** [comment]
Danke!

Ich habe mit der tatsächlichen Anzahl gearbeitet (10) und egal ob ich math.max oder direkt _n ausgelelesen habe, das Ergebnis war immer 10. Dass das aber die 9. Stelle ist habe ich dabei total übersehen. 

Solved.
